name: Releaser
on: 
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  mac:
    name: Build for macOS
    runs-on: macos-latest
    outputs:
      artifact: ${{ steps.package.outputs.artifact }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build on macOS
        run: cargo build --release

      - name: Copy artifact
        run: cp target/release/hx .

      - name: Zip artifact
        run: tar -czf horcrust-${{ github.ref_name }}-apple-darwin.tar.gz hx LICENSE
      - id: package
        name: Output the artifact
        run: echo "artifact=horcrust-${{ github.ref_name }}-apple-darwin.tar.gz" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package.outputs.artifact }}
          path: ${{ steps.package.outputs.artifact }}
  linux:
    name: Build for linux
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.package.outputs.artifact }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build on linux
        run: cargo build --release

      - name: Copy artifact
        run: cp target/release/hx .
      - name: Zip artifact
        run: tar -czf horcrust-${{ github.ref_name }}-x86_64-unknown-linux-musl.tar.gz hx LICENSE
      - id: package
        name: Output the artifact
        run: echo "artifact=horcrust-${{ github.ref_name }}-x86_64-unknown-linux-musl.tar.gz" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package.outputs.artifact }}
          path: ${{ steps.package.outputs.artifact }}
  windows:
    name: Build for windows
    runs-on: windows-latest
    outputs:
      artifact: ${{ steps.package.outputs.artifact }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build on windows
        run: cargo build --release

      - name: Create artifact folder
        run: |
          mkdir artifact
          cp "target/release/hx.exe" artifact/
          cp "LICENSE" artifact/
        working-directory: ${{ github.workspace }}

      - name: Zip artifact
        run: Compress-Archive -Path "artifact/*" -DestinationPath "horcrust-${{ github.ref_name }}-x86_64-pc-windows-msvc.zip"
        working-directory: ${{ github.workspace }}
      
      - id: package
        name: Output the artifact
        run: echo ("artifact=horcrust-${{ github.ref_name }}-x86_64-pc-windows-msvc.zip") >> $env:GITHUB_OUTPUT
      - name: test
        run: |
          dir
          echo ${{ steps.package.outputs.artifact }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package.outputs.artifact }}
          path: ${{ steps.package.outputs.artifact }}
  
  release:
    name: Create GitHub Release
    needs: [mac, windows, linux]
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release file
        run: echo ${{ github.sha }} > RELEASE.txt
      - name: Download mac artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{needs.mac.outputs.artifact}}
      - name: Download linux artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{needs.linux.outputs.artifact}}
      - name: Download windows artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{needs.windows.outputs.artifact}}
      - name: Test
        run: |
          cat RELEASE.txt
          ls
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: v1.0.0
          tag_name: v1.0.0
          files: |
            ${{ needs.mac.outputs.artifact }}
            ${{ needs.linux.outputs.artifact }}
            ${{ needs.windows.outputs.artifact }}
            RELEASE.txt
            LICENSE
  